### ISSUE TITLE
Performance improvement in AbstractSchemaTranslator.addAttributeTypes() method

### ISSUE THREAD

**Issue by elecharny** [Evolveum/connector-ldap#5]
The addAttributeTypes() method uses a List<AttributeInfo> parameter to store the translated AttributeTypes. Froma performance POV, this is clearly a wrong choice, as we will loop on all the MUST and MAY attributes to add the attributeTypes into the list by looping on this list in the containsAttribute() method. 

I see two problems : 
- first the list will grow up to the number of AT (468 in a default ApacheDS setup), which means we will check the presence of attribute 468/2 * 468 times (109512 checks)
- second we are also lookup for the OC superiors, and will loop again may times for nothing , assuming we will already loop for the superior OC.

Using a TreeMap to gather the AT is probably a better idea : it's ordered, and lookups are O(log(n)). But overall, we probably just need a Map, as the resulting list is just used to feed the ObjectClassInfoBuilder, and the order is not mandated.

**Comment by semancik** [comment]
Yes. Of course, you are right. However this issue is not that bad. The connector instances are pooled and they cache processed schema. Therefore we suffer performance hit only on the first operation when the schema is processed. Translated schema (ConnId schema) is working with attribute definitions per objectclass, it does not have global attribute definitions. So after the first operation the hit should be quite mild.
We will need to fix it eventually. But it can wait a bit. Especially if we need a fix in ConnId framework or Directory API. There are more fixes that we need in the directory API (e.g. getting rid of those annoying schema errors when using AD). But that needs to wait as that will need a larger update of the API error handling code. Let's do it after the API 1.0.0 release.

**Comment by elecharny** [comment]
Actually, the fix is trivial and does not impact ConnId. The gain is almost unnoticable though : 3ms, compared to the 700 ms it takes to parse the schema :-)

I'll push a PR for it, up to you to apply it.

**Comment by semancik** [comment]
OK. that makes sense. Thanks.

**Comment by elecharny** [comment]
The thing is that loading the schema is atrociously slow. This is due to the Description parsing, done with Antlr. All in all, this is something that can be improved in the LDAP API.

In any case, that's not related to the ldap connector.

**Comment by elecharny** [comment]
The code has been fixed.
